#!/bin/sh
set -eu
PACMAN=$1; shift
PACKAGES=$(cat | ./pacman/translate)

# Hash sources list
SOURCES_KEY=$("$PACMAN-conf" --repo-list 2>/dev/null | xargs -n1 "$PACMAN-conf" --repo | sha256sum | cut -d' ' -f1)

# Filter installed packages
INSTALLED=$("$PACMAN" -Qq)
INSTALLED_KEY=$(echo "$INSTALLED" | sha256sum | cut -d' ' -f1)
# shellcheck disable=SC2086
PACKAGES=$(echo "$INSTALLED" | ./exclude $PACKAGES | sort | xargs echo)

# Output manifest
echo "$SOURCES_KEY:$INSTALLED_KEY:$PACKAGES"
