#!/bin/sh

# Detect `sudo`
SUDO=
if command -v sudo >/dev/null 2>&1; then
	SUDO=sudo
fi

# apt-get[canonical]
if command -v apt-get >/dev/null 2>&1; then
  $SUDO apt-get -qq update
  # shellcheck disable=SC2046
  $SUDO apt-get -qq install -y $(cat)
  exit
fi

# apk[alpine]
if command -v apk >/dev/null 2>&1; then
  # shellcheck disable=SC2046
  $SUDO apk add $(
    cat | while read -r NAME; do
      case "$NAME" in
        build-essential) echo build-base ;;
        dnsutils) echo bind-tools ;;
        libboost-all-dev) echo boost-dev ;;
        ninja-build) echo ninja ;;
        pkg-config) echo pkgconf ;;
        ssh) echo openssh ;;
        *) echo "$NAME" ;;
      esac
    done
  )
  exit
fi

exit 1
