#!/bin/sh
set -eu

matches() {
  TARGET=${1%#*}
  if [ "$TARGET" = "$1" ]; then
    echo "$1"
    return 0
  elif [ "$TARGET" = "$PROFILE" ]; then
    echo "${1#*#}"
    return 0
  else
    return 1
  fi
}

# apt-get[canonical]
if command -v apt-get >/dev/null 2>&1; then
  PROFILE=debian
  echo apt:
  cat | while read -r PATTERN; do
    if ! NAME=$(matches "$PATTERN"); then continue; fi
    echo "$NAME"
  done
  exit
fi

# apk[alpine]
if command -v apk >/dev/null 2>&1; then
  PROFILE=alpine
  echo apk:
  cat | while read -r PATTERN; do
    if ! NAME=$(matches "$PATTERN"); then continue; fi
    case "$NAME" in
      build-essential) echo build-base ;;
      clang-[0-9]*) echo "clang${NAME##*-}" ;;
      clang-tools-[0-9]*) echo "clang${NAME##*-}-extra-tools" ;;
      dnsutils) echo bind-tools ;;
      libboost-all-dev) echo boost-dev ;;
      lld-[0-9]*) echo "lld${NAME##*-}" ;;
      llvm-[0-9]*) echo "llvm${NAME##*-}" ;;
      ninja-build) echo ninja-is-really-ninja ;;
      ssh) echo openssh ;;
      xz-utils) echo xz ;;
      *) echo "$NAME" ;;
    esac
  done
  exit
fi

exit 1
