#!/bin/sh
set -eu
SOURCES_KEY=$1; shift
SOURCES_TAR=$1; shift
PACKAGES_TAR=$1; shift
SUDO=$(command -v sudo 2>/dev/null || echo eval)

# Update sources
MANIFEST_KEY=$(cat /var/cache/apt/heritage 2>/dev/null || true)
if [ "$MANIFEST_KEY" != "$SOURCES_KEY" ]; then
	if [ "$SOURCES_TAR" = - ]; then
		echo ::group::Update [no cache]
		$SUDO apt-get -q update
		echo ::endgroup::
	elif [ -f "$SOURCES_TAR" ]; then
		echo ::group::Update [cache hit]
		$SUDO tar xf "$SOURCES_TAR" -C /
		echo ::endgroup::
	else
		echo ::group::Update [cache miss]
		$SUDO apt-get -q update
		$SUDO rm /var/lib/apt/lists/lock
		$SUDO rmdir /var/lib/apt/lists/partial
		tar cf "$SOURCES_TAR" -C / var/lib/apt/lists
		echo ::endgroup::
	fi
fi

# Install packages
SPAM_EXPR="^Preparing to unpack|^Unpacking|^Selecting previously unselected package|^\(Reading database"
if [ "$PACKAGES_TAR" = - ]; then
	echo ::group::Install [no cache]
	mkfifo .stdout
	trap 'rm -f .stdout' EXIT
	grep -Ev "$SPAM_EXPR" < .stdout | cat &
	$SUDO DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends -y "$@" > .stdout
	echo ::endgroup::
elif [ -f "$PACKAGES_TAR" ]; then
	echo ::group::Install [cache hit]
	$SUDO tar xf "$PACKAGES_TAR" -C /
	mkfifo .stdout
	trap 'rm -f .stdout' EXIT
	grep -Ev "$SPAM_EXPR" < .stdout | cat &
	$SUDO DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends -y "$@" > .stdout
	echo ::endgroup::
else
	echo ::group::Install [cache miss]
	mkfifo .stdout
	trap 'rm -f .stdout' EXIT
	grep -Ev "$SPAM_EXPR" < .stdout | cat &
	$SUDO apt-get -qq install --no-install-recommends --download-only -y "$@" > .stdout
	$SUDO rm /var/cache/apt/archives/lock
	$SUDO rmdir /var/cache/apt/archives/partial
	tar cf "$PACKAGES_TAR" -C / var/cache/apt/archives
	grep -Ev "$SPAM_EXPR" < .stdout | cat &
	$SUDO DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends -y "$@" > .stdout
	echo ::endgroup::
fi
