#!/bin/sh
set -eu
APT=$1; shift
SOURCES_TAR=$1; shift
PACKAGES_TAR=$1; shift
SUDO=$(command -v sudo || echo eval)

# Update sources
if [ "$SOURCES_TAR" = - ]; then
	echo ::group::Update [no cache]
	$SUDO "$APT" -q update
	echo ::endgroup::
elif [ -f "$SOURCES_TAR" ]; then
	echo ::group::Update [cache hit]
	$SUDO tar xf "$SOURCES_TAR" -C /
	echo ::endgroup::
else
	echo ::group::Update [cache miss]
	$SUDO "$APT" -q update
	$SUDO rm /var/lib/apt/lists/lock
	$SUDO rmdir /var/lib/apt/lists/partial
	tar cf "$SOURCES_TAR" -C / var/lib/apt/lists
	echo ::endgroup::
fi

# Install packages
SPAM_EXPR="^Preparing to unpack|^Unpacking|^Selecting previously unselected package|^\(Reading database"
if [ "$PACKAGES_TAR" = - ]; then
	echo ::group::Install [no cache]
elif [ -f "$PACKAGES_TAR" ]; then
	echo ::group::Install [cache hit]
	$SUDO tar xf "$PACKAGES_TAR" -C /
else
	echo ::group::Install [cache miss]
	mkfifo .stdout
	trap 'rm -f .stdout' EXIT
	grep -Ev "$SPAM_EXPR" < .stdout | cat &
	$SUDO "$APT" -qq install --no-install-recommends --download-only -y "$@" > .stdout
	$SUDO rm /var/cache/apt/archives/lock
	$SUDO rmdir /var/cache/apt/archives/partial
	tar cf "$PACKAGES_TAR" -C / var/cache/apt/archives
	grep -Ev "$SPAM_EXPR" < .stdout | cat &
	$SUDO DEBIAN_FRONTEND=noninteractive "$APT" -qq install --no-install-recommends -y "$@" > .stdout
	rm .stdout
fi
mkfifo .stdout
trap 'rm -f .stdout' EXIT
grep -Ev "$SPAM_EXPR" < .stdout | cat &
$SUDO DEBIAN_FRONTEND=noninteractive "$APT" -qq install --no-install-recommends -y "$@" > .stdout
echo ::endgroup::
