#!/bin/sh
set -eu
SOURCES_KEY=$1; shift
SOURCES_TAR=$1; shift
PACKAGES_TAR=$1; shift
SUDO=$(command -v sudo 2>/dev/null || true)

# Update sources
MANIFEST_KEY=$(cat /var/cache/apk/heritage 2>/dev/null || true)
if [ "$MANIFEST_KEY" != "$SOURCES_KEY" ]; then
	if [ "$SOURCES_TAR" = - ]; then
		echo ::group::Update [no cache]
		$SUDO apk update
		echo ::endgroup::
	elif [ -f "$SOURCES_TAR" ]; then
		echo ::group::Update [cache hit]
		$SUDO tar xfv "$SOURCES_TAR" --overwrite -C /
		echo ::endgroup::
	else
		echo ::group::Update [cache miss]
		$SUDO apk update
		tar cfv "$SOURCES_TAR" -C / var/cache/apk
		echo ::endgroup::
	fi
fi

# Install packages
# nb: `tar` added for cache action compatibility
if [ "$PACKAGES_TAR" = - ]; then
	echo ::group::Install [no cache]
	$SUDO apk add "$@"
	echo ::endgroup::
else
	rm -rf ~/.install
	mkdir ~/.install
	if [ -f "$PACKAGES_TAR" ]; then
		echo ::group::Install [cache hit]
		$SUDO tar xfv "$PACKAGES_TAR" --overwrite -C ~/.install
		$SUDO apk add ~/.install/*.apk
		echo ::endgroup::
	else
		echo ::group::Install [cache miss]
		apk fetch -R --output ~/.install "$@"
		tar cvf "$PACKAGES_TAR" -C ~/.install .
		$SUDO apk add ~/.install/*.apk
		echo ::endgroup::
	fi
	rm -rf ~/.install/*
fi
