#!/bin/sh
set -eu
PACKAGES=$(cat)

# Hash sources list
SOURCES_KEY=$(sha256sum < /etc/apk/repositories | cut -d' ' -f1)

# Filter installed packages
INSTALLED=$(apk info 2>/dev/null)
INSTALLED_KEY=$(echo "$INSTALLED" | sha256sum | cut -d' ' -f1)
# shellcheck disable=SC2086
PACKAGES=$(echo "$INSTALLED" | ./exclude $PACKAGES | sort | xargs echo)

# Output manifest
echo "$SOURCES_KEY:$INSTALLED_KEY:$PACKAGES"
