name: Test
on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        host:
          - os: ubuntu-latest
            tool: auto
            packages: ca-certificates curl git
          - os: ubuntu-latest
            container: debian:sid
            tool: auto
            packages: ca-certificates curl git
          - os: ubuntu-latest
            container: alpine
            tool: auto
            packages: ca-certificates curl git
          - os: ubuntu-latest
            container: archlinux
            tool: auto
            packages: ca-certificates curl git
          - os: windows-2025-vs2026
            tool: /c/msys64/usr/bin/pacman
            packages: mingw64/mingw-w64-%a-ninja

    name: ${{ matrix.host.os }} ${{ matrix.host.container }}
    runs-on: ${{ matrix.host.os }}
    container: ${{ matrix.host.container }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./apt/sources
        if: matrix.host.tool == 'apt'
        with:
          name: nodesource24
          source: |
            Types: deb
            URIs: https://deb.nodesource.com/node_24.x
            Suites: nodistro
            Components: main
            Signed-By: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key

      - uses: ./
        with:
          tool: ${{ matrix.host.tool }}
          packages: ${{ matrix.host.packages }}
